apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tms-backend-pvc
  namespace: tms-backend
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-ceph-cephfs
  resources:
    requests:
      storage: 20Gi
