apiVersion: v1
kind: Secret
metadata:
  name: nexus-regcred
  namespace: tms-backend
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL25leHVzLnN1cGVycGFydC5jby50aCI6eyJ1c2VybmFtZSI6ImRldmVsb3BlciIsInBhc3N3b3JkIjoiQ2xvdWR5JERheTczIU9yYW5nZSIsImF1dGgiOiJaR1YyWld4dmNHVnk6UTJ4dmRXUTVSREY1TnpNdEExSmhiaGNnIn19fQ==
